export const GET_ALL_MOVIES_REQUEST = 'GET_ALL_MOVIES_REQUEST';
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_FAILURE = 'GET_ALL_MOVIES_FAILURE';

export const GET_MOVIES_BY_ID_REQUEST = 'GET_MOVIES_BY_ID_MOVIES_REQUEST';
export const GET_MOVIES_BY_ID_SUCCESS = 'GET_MOVIES_BY_ID_SUCCESS';
export const GET_MOVIES_BY_ID_FAILURE = 'GET_MOVIES_BY_ID_FAILURE';
