import axios from 'axios';
import { Movie } from './movie';

const API_URL = 'https://api.example.com';

export const getMovieByIdData = async (id: number): Promise<Movie> => {
    // const response = await axios.get(`${API_URL}/todos/${id}`);
    // return response.data;
    return {
        id: '1',
        title: 'Deadpool & Wolverine',
        description: 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
        genre: ['Superhero', 'Action', 'Comedy'],
        year: 2024,
        duration: '1h 59m',
        coverUrl: 'https://image.tmdb.org/t/p/original/9l1eZiJHmhr5jIlthMdJN5WYoff.jpg',
        backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
        logoUrl: 'https://image.tmdb.org/t/p/original/iELasLmGIX5JyjqrmL19ZoG8ITG.png',        
    };
}

export const getMovieData = async (): Promise<{ recommended: Movie[], newDisney: Movie[], originals: Movie[], trending: Movie[] }> => {
    // const response = await axios.get(`${API_URL}/todos`);
    // return response.data;
    return {
        recommended: [{
            id: '1',
            title: 'Inside Out 2',
            description: 'Recommended Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/9l1eZiJHmhr5jIlthMdJN5WYoff.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '2',
            title: 'new Disney Movie Title',
            description: 'new Disney Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/coATv42PoiLqAFKStJiMZs2r6Zb.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '3',
            title: 'originals Movie Title',
            description: 'originals Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/5zmiBoMzeeVdQ62no55JOJMY498.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '4',
            title: 'High School Musical',
            description: 'Troy, the popular captain of the basketball team, and Gabriella, the brainy and beautiful member of the academic club, break all the rules of East High society when they secretly audition for the leads in the school’s musical. As they reach for the stars and follow their dreams, everyone learns about acceptance, teamwork, and being yourself.',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/jNjT5y95BToczcxgVPl1NBB7goY.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '5',
            title: 'High School Musical',
            description: 'Troy, the popular captain of the basketball team, and Gabriella, the brainy and beautiful member of the academic club, break all the rules of East High society when they secretly audition for the leads in the school’s musical. As they reach for the stars and follow their dreams, everyone learns about acceptance, teamwork, and being yourself.',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/askg3SMvhqEl4OL52YuvdtY40Yb.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        }],
        newDisney: [{
            id: '1',
            title: 'Inside Out 2',
            description: 'Recommended Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/9l1eZiJHmhr5jIlthMdJN5WYoff.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '2',
            title: 'new Disney Movie Title',
            description: 'new Disney Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/coATv42PoiLqAFKStJiMZs2r6Zb.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '3',
            title: 'originals Movie Title',
            description: 'originals Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/5zmiBoMzeeVdQ62no55JOJMY498.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '4',
            title: 'High School Musical',
            description: 'Troy, the popular captain of the basketball team, and Gabriella, the brainy and beautiful member of the academic club, break all the rules of East High society when they secretly audition for the leads in the school’s musical. As they reach for the stars and follow their dreams, everyone learns about acceptance, teamwork, and being yourself.',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/jNjT5y95BToczcxgVPl1NBB7goY.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '5',
            title: 'High School Musical',
            description: 'Troy, the popular captain of the basketball team, and Gabriella, the brainy and beautiful member of the academic club, break all the rules of East High society when they secretly audition for the leads in the school’s musical. As they reach for the stars and follow their dreams, everyone learns about acceptance, teamwork, and being yourself.',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/askg3SMvhqEl4OL52YuvdtY40Yb.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        }],
        originals: [{
            id: '1',
            title: 'Inside Out 2',
            description: 'Recommended Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/9l1eZiJHmhr5jIlthMdJN5WYoff.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '2',
            title: 'new Disney Movie Title',
            description: 'new Disney Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/coATv42PoiLqAFKStJiMZs2r6Zb.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '3',
            title: 'originals Movie Title',
            description: 'originals Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/5zmiBoMzeeVdQ62no55JOJMY498.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '4',
            title: 'High School Musical',
            description: 'Troy, the popular captain of the basketball team, and Gabriella, the brainy and beautiful member of the academic club, break all the rules of East High society when they secretly audition for the leads in the school’s musical. As they reach for the stars and follow their dreams, everyone learns about acceptance, teamwork, and being yourself.',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/jNjT5y95BToczcxgVPl1NBB7goY.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '5',
            title: 'High School Musical',
            description: 'Troy, the popular captain of the basketball team, and Gabriella, the brainy and beautiful member of the academic club, break all the rules of East High society when they secretly audition for the leads in the school’s musical. As they reach for the stars and follow their dreams, everyone learns about acceptance, teamwork, and being yourself.',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/askg3SMvhqEl4OL52YuvdtY40Yb.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        }],
        trending: [{
            id: '1',
            title: 'Inside Out 2',
            description: 'Recommended Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/9l1eZiJHmhr5jIlthMdJN5WYoff.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '2',
            title: 'new Disney Movie Title',
            description: 'new Disney Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/coATv42PoiLqAFKStJiMZs2r6Zb.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '3',
            title: 'originals Movie Title',
            description: 'originals Movie Description',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/5zmiBoMzeeVdQ62no55JOJMY498.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '4',
            title: 'High School Musical',
            description: 'Troy, the popular captain of the basketball team, and Gabriella, the brainy and beautiful member of the academic club, break all the rules of East High society when they secretly audition for the leads in the school’s musical. As they reach for the stars and follow their dreams, everyone learns about acceptance, teamwork, and being yourself.',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/jNjT5y95BToczcxgVPl1NBB7goY.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        },
        {
            id: '5',
            title: 'High School Musical',
            description: 'Troy, the popular captain of the basketball team, and Gabriella, the brainy and beautiful member of the academic club, break all the rules of East High society when they secretly audition for the leads in the school’s musical. As they reach for the stars and follow their dreams, everyone learns about acceptance, teamwork, and being yourself.',
            genre: ['Superhero', 'Action', 'Comedy'],
            year: 2024,
            duration: '1h 59m',
            coverUrl: 'https://image.tmdb.org/t/p/original/askg3SMvhqEl4OL52YuvdtY40Yb.jpg',
            backgroundUrl: 'https://image.tmdb.org/t/p/original/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
            logoUrl: 'https://image.tmdb.org/t/p/original/5Z8WWr0eY5zr7xLhJb3q0q2Q1jz.jpg',
        }]
    };    
};
